In [1]:
import pandas as pd
import numpy as np

In [2]:
#יש לטעון את רשימת הקיניות מהקובץ - האינדקס הוא מספר ההזמנה
df = pd.read_csv('supermarket_sales.csv', index_col=0)

In [18]:
#הראו 5 שורות ראשונות
df.head(5)

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
Invoice ID,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [19]:
#הציגו את רשימת העמודות
df.columns

Index(['Branch', 'City', 'Customer type', 'Gender', 'Product line',
       'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date', 'Time', 'Payment',
       'cogs', 'gross margin percentage', 'gross income', 'Rating'],
      dtype='str')

In [20]:
#כתבו כמה ערים יש וכמה יש בכל עיר
df['City'].nunique()

df['City'].value_counts()

City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64

In [23]:
#יש ליצור את טבלאת הפיבוט הבאה, שימו לב כל הערכים זה ממוצעים
pivot = df.pivot_table(
    values=['Quantity','Rating','Tax 5%','Total','Unit price','cogs','gross income','gross margin percentage'],
    index='City',
    aggfunc='mean'
)
pivot

,Quantity,Rating,Tax 5%,Total,Unit price,cogs,gross income,gross margin percentage
City,,,,,,,,
Mandalay,5.481928,6.818072,15.232024,319.872506,55.659277,304.640482,15.232024,4.761905
Naypyitaw,5.582317,7.072866,16.052367,337.099715,56.609024,321.047348,16.052367,4.761905
Yangon,5.467647,7.027059,14.874001,312.354031,54.780853,297.480029,14.874001,4.761905

In [24]:
# ייצרו את טבלאת הפיבוט הבאה, שימו לב החישוב הוא סכום העמודות
pivot2 = df.pivot_table(
    values=['Rating','gross income'],
    index='City',
    aggfunc='sum'
)
pivot2

           Rating  gross income
City
Mandalay   2263.6     5057.0320
Naypyitaw  2319.9     5265.1765
Yangon     2389.2     5057.1605

In [31]:
#בצעו את אותה טבלא, אבל לעמודה הראשונה יש לחשב ערך מקסימלי ולשניה סטיית תקן
pivot3 = df.pivot_table(
    values=['Rating','gross income'],
    index='City',
    aggfunc={'Rating':np.std,'gross income':np.max}
)
pivot3

             Rating  gross income
City
Mandalay   1.711136         48.69
Naypyitaw  1.701925         49.65
Yangon     1.728797         49.49

In [35]:
#יש להראות בכל עיר את ממוצע המדד לגברים ןלנשים ואת ממוצע ההכנסה הכללית לגבר ונשים
#מדד- rating
#ממוצע הכנסה - gross income
pivot4 = df.pivot_table(
    values=['Rating','gross income'],
    index='City',
    columns="Gender",
    aggfunc='mean'
)
pivot4

             Rating           gross income
Gender       Female      Male       Female       Male
City
Mandalay   6.876543  6.762353    15.557994  14.921394
Naypyitaw  7.157865  6.972000    16.502264  15.518490
Yangon     6.839130  7.196089    15.755447  14.081193

In [36]:
#יש להראות בכל מגדר את סטיית התקן של הכמות ומחיר יחידה בחתך כל עיר
pivot5 = df.pivot_table(
    values=['Quantity','Unit price'],
    index='City',
    columns="Gender",
    aggfunc=np.std
)
pivot5

           Quantity           Unit price
Gender       Female      Male     Female       Male
City
Mandalay   2.841525  2.933101  26.826657  25.477543
Naypyitaw  2.999037  2.996858  27.568719  26.560459
Yangon     2.785075  2.908378  27.023160  25.170655