In [1]:
import pandas as pd
import numpy as np

In [3]:
#יש לטעון את רשימת הקיניות מהקובץ - האינדקס הוא מספר ההזמנה

In [1]:
#הראו 5 שורות ראשונות

In [2]:
#הציגו את רשימת העמודות

In [ ]:
#כתבו כמה ערים יש וכמה יש בכל עיר

In [11]:
#יש ליצור את טבלאת הפיבוט הבאה, שימו לב כל הערכים זה ממוצעים

,Quantity,Rating,Tax 5%,Total,Unit price,cogs,gross income,gross margin percentage
City,,,,,,,,
Mandalay,5.481928,6.818072,15.232024,319.872506,55.659277,304.640482,15.232024,4.761905
Naypyitaw,5.582317,7.072866,16.052367,337.099715,56.609024,321.047348,16.052367,4.761905
Yangon,5.467647,7.027059,14.874001,312.354031,54.780853,297.480029,14.874001,4.761905

In [12]:
#כתבו כמה ערים יש וכמה יש בכל עיר

In [19]:
# ייצרו את טבלאת הפיבוט הבאה, שימו לב החישוב הוא סכום העמודות

           Rating  gross income
City
Mandalay   2263.6     5057.0320
Naypyitaw  2319.9     5265.1765
Yangon     2389.2     5057.1605

In [21]:
#בצעו את אותה טבלא, אבל לעמודה הראשונה יש לחשב ערך מקסימלי ולשניה סטיית תקן

             Rating  gross income
City
Mandalay   1.713719         48.69
Naypyitaw  1.704526         49.65
Yangon     1.731345         49.49

In [24]:
#יש להראות בכל עיר את ממוצע המדד לגברים ןלנשים ואת ממוצע ההכנסה הכללית לגבר ונשים
#מדד- rating
#ממוצע הכנסה - gross income

           Rating         gross income
Gender     Female    Male       Female       Male
City
Mandalay   1114.0  1149.6     2520.395  2536.6370
Naypyitaw  1274.1  1045.8     2937.403  2327.7735
Yangon     1101.1  1288.1     2536.627  2520.5335

In [3]:
#יש להראות בכל מגדר את סטיית התקן של הכמות ומחיר יחידה בחתך כל עיר